# Generated by Django 4.0.4 on 2023-05-23 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postlike",
            old_name="user",
            new_name="author",
        ),
    ]
