# Generated by Django 4.0.4 on 2023-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                max_length=250, unique=True, unique_for_date="title"
            ),
        ),
    ]
