# Generated by Django 4.0.4 on 2023-05-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_post_image_alter_post_video"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
