# Generated by Django 4.0.4 on 2023-05-25 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0007_post_likes_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(default="username", max_length=63, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together={("author", "post")},
        ),
    ]
