# Generated by Django 4.0.4 on 2023-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_profile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(related_name="following", to="app.profile"),
        ),
    ]
