# Generated by Django 4.0.4 on 2023-06-07 17:39

import app.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_post_image_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='Test', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(app.models.post_image_file_path, *('profiles',), **{}), verbose_name='Avatar'),
        ),
    ]
